chore: fixed typo and instance data structure
spacebarchat/community-instances pull request #68
Opened 2023-07-17 00:24 UTC by BRGustavoRibeiro

- The 'official' tag has been renamed to 'verified', as it can help official support to long-term, serious and well-established instances in the future.
- The 'display' tag has been added in case an instance admin wants to hide itself from the website without needing to remove it from the list (for temporary reasons, like an instance overload or extremely high usage, for example. Lemmy suffered from this problem a few weeks ago).

2023-07-17 23:13 UTC, MaddyUnderStars approved these changes

2023-08-13 10:03 UTC, MaddyUnderStars requested changes

2023-08-13 10:03 UTC, MaddyUnderStars commented on instances.json
> +    "language": "pt"
brazil? portuguese? the official instance is located in the the EU and is english-only

2023-08-13 17:36 UTC, BRGustavoRibeiro commented on instances.json
> +    "language": "pt"
Sorry, I confused myself

This was written when I was tired af and coding almost asleep 🫠
Will fix

2023-08-13 17:39 UTC, BRGustavoRibeiro commented on instances.json
> +    "language": "xx"
I was probably following the [ISO 3166-1 alpha-2, where XX](
https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#XX) is used by WIPO to design unknown states, entities or organizations.

But I agree that _undefined_ would be a better fit. Will fix

2023-08-14 02:33 UTC, MaddyUnderStars commented
thank you!

2023-08-14 02:33 UTC, merged